trigger:
  - main

variables:
  - group: stock_analysis_secret
  - name: pythonVersion
    value: '3.x'
  - name: scriptPath
    value: 'deploy_pbix.py'
  - name: pbixFilePath
    value: 'stock.pbix'

stages:
  - stage: Development
    displayName: 'Deploy to Development Workspace'
    jobs:
      - job: DeployReportToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
          - script: |
              python --version
              which python
            displayName: 'Validate Python Installation'
          - script: |
              python $(scriptPath) --client_id $(client_id) --tenant_id $(tenant_id) --secret_id $(secret_id) --workspace_id $(dev_workspace_id) --pbix_path $(pbixFilePath)
            displayName: 'Deploy Power BI Report to Development'

  - stage: Test
    dependsOn: Development
    condition: succeeded()
    displayName: 'Deploy to Test Workspace'
    jobs:
      - job: DeployReportToTest
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
          - script: |
              python --version
              which python
            displayName: 'Validate Python Installation'
          - script: |
              python $(scriptPath) --client_id $(client_id) --tenant_id $(tenant_id) --secret_id $(secret_id) --workspace_id $(test_workspace_id) --pbix_path $(pbixFilePath)
            displayName: 'Deploy Power BI Report to Test'

  - stage: Production
    dependsOn: Test
    condition: succeeded()
    displayName: 'Deploy to Production Workspace'
    jobs:
      - job: DeployReportToProd
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
          - script: |
              python --version
              which python
            displayName: 'Validate Python Installation'
          - script: |
              python $(scriptPath) --client_id $(client_id) --tenant_id $(tenant_id) --secret_id $(secret_id) --workspace_id $(prod_workspace_id) --pbix_path $(pbixFilePath)
            displayName: 'Deploy Power BI Report to Production'